export const CITY_LANDMARKS: { [key: string]: string } = {
  // Default image
  'default': 'modern city skyline sunset',

  // France - Major Cities
  'paris': 'eiffel tower paris',
  'marseille': 'notre dame de la garde marseille',
  'lyon': 'place bellecour basilica fourviere lyon',
  'toulouse': 'carmes toulouse',
  'nice': 'promenade des anglais nice',
  'nantes': 'machines de l\'ile elephant nantes',
  'strasbourg': 'cathedral petite france strasbourg',
  'montpellier': 'place de la comedie montpellier',
  'bordeaux': 'place de la bourse miroir d\'eau bordeaux',
  'lille': 'grand place vieille bourse lille',
  'rennes': 'place parlement bretagne rennes',
  'reims': 'cathedral notre dame reims',
  'saint-etienne': 'place jean jaures saint etienne',
  'toulon': 'port rade toulon',
  'le havre': 'port volcan le havre',
  'grenoble': 'bastille telepherique grenoble',
  'dijon': 'palace ducs dijon',
  'angers': 'chateau angers',
  'villeurbanne': 'gratte ciel villeurbanne',
  'le mans': 'cathedral saint julien le mans',
  'aix-en-provence': 'rotonde fountain aix en provence',
  'brest': 'port chateau brest',
  'limoges': 'cathedral saint etienne limoges',
  'tours': 'place plumereau tours',
  'amiens': 'cathedral notre dame amiens',
  'perpignan': 'palace kings majorca perpignan',
  'metz': 'cathedral saint etienne metz',
  'besancon': 'citadelle vauban besancon',
  'orleans': 'cathedral sainte croix orleans',
  'rouen': 'cathedral notre dame rouen',
  'avignon': 'palais des papes avignon',
  'caen': 'chateau ducal caen',
  'clermont-ferrand': 'cathedral notre dame clermont ferrand',
  'mulhouse': 'place reunion mulhouse',
  'dunkerque': 'beffroi dunkerque',
  'calais': 'hotel de ville calais',
  'belfort': 'lion belfort',
  'arles': 'amphitheatre arenes arles',
  'cherbourg': 'theatre italien cherbourg',
  'pau': 'chateau pau',
  'bayonne': 'cathedral sainte marie bayonne',
  'lorient': 'port lorient',
  'saint-malo': 'remparts saint malo',
  'la rochelle': 'vieux port tours la rochelle',
  'cannes': 'palais festivals croisette cannes',
  'antibes': 'fort carre antibes',
  'colmar': 'petite venise colmar',

  // Europe
  'london': 'big ben london',
  'rome': 'colosseum rome',
  'barcelona': 'sagrada familia barcelona',
  'amsterdam': 'canal houses dam square amsterdam',
  'berlin': 'brandenburg gate berlin',
  'vienna': 'schonbrunn palace vienna',
  'venice': 'saint marks basilica venice',
  'athens': 'acropolis parthenon athens',
  'madrid': 'royal palace plaza mayor madrid',
  'lisbon': 'belem tower lisbon',
  'prague': 'charles bridge prague castle',
  'budapest': 'parliament building budapest',
  'copenhagen': 'nyhavn copenhagen',
  'stockholm': 'gamla stan stockholm',
  'oslo': 'opera house oslo',
  'helsinki': 'cathedral senate square helsinki',
  'dublin': 'trinity college dublin',
  'brussels': 'grand place brussels',
  'zurich': 'grossmunster zurich',
  'geneva': 'jet d\'eau geneva',
  'monaco': 'monte carlo casino monaco',
  'vatican city': 'st peters basilica vatican',
  'krakow': 'wawel castle krakow',
  'porto': 'dom luis bridge porto',
  'seville': 'plaza de espana seville',
  'florence': 'duomo cathedral florence',
  'naples': 'mount vesuvius naples',
  'palermo': 'cathedral palermo',
  'hamburg': 'elbphilharmonie hamburg',
  'frankfurt': 'romer frankfurt',
  'munich': 'marienplatz munich',
  'rotterdam': 'erasmus bridge rotterdam',
  'valencia': 'city of arts sciences valencia',
  'milan': 'duomo cathedral milan',
  'turin': 'mole antonelliana turin',
  'warsaw': 'palace of culture warsaw',
  'bucharest': 'parliament palace bucharest',
  'belgrade': 'saint sava temple belgrade',
  'sofia': 'alexander nevsky cathedral sofia',
  'zagreb': 'st marks church zagreb',
  'bratislava': 'bratislava castle',
  'ljubljana': 'triple bridge ljubljana',
  'tallinn': 'old town tallinn',
  'riga': 'house of blackheads riga',
  'vilnius': 'gediminas tower vilnius',
  'reykjavik': 'hallgrimskirkja reykjavik',
  'malta': 'st johns cathedral valletta',
  'nicosia': 'buyuk han nicosia',
  'andorra': 'casa de la vall andorra',

  // Americas
  'new york': 'statue of liberty empire state new york',
  'los angeles': 'hollywood sign los angeles',
  'chicago': 'cloud gate bean millennium park chicago',
  'toronto': 'cn tower toronto',
  'vancouver': 'stanley park vancouver',
  'montreal': 'notre dame basilica montreal',
  'san francisco': 'golden gate bridge san francisco',
  'rio de janeiro': 'christ the redeemer rio',
  'buenos aires': 'casa rosada buenos aires',
  'mexico city': 'palace of fine arts mexico city',
  'havana': 'capitol building havana',
  'lima': 'plaza mayor lima',
  'santiago': 'plaza de armas santiago',
  'bogota': 'monserrate bogota',
  'sao paulo': 'ibirapuera park sao paulo',
  'quebec city': 'chateau frontenac quebec',
  'washington dc': 'capitol building washington dc',
  'las vegas': 'strip bellagio fountain las vegas',
  'miami': 'south beach ocean drive miami',
  'seattle': 'space needle seattle',
  'boston': 'faneuil hall boston',
  'philadelphia': 'liberty bell philadelphia',
  'houston': 'space center houston',
  'dallas': 'reunion tower dallas',
  'atlanta': 'centennial olympic park atlanta',
  'denver': 'red rocks amphitheatre denver',
  'portland': 'portland japanese garden',
  'austin': 'texas state capitol austin',
  'nashville': 'broadway street nashville',
  'new orleans': 'french quarter bourbon street',
  'san diego': 'balboa park san diego',
  'phoenix': 'desert botanical garden phoenix',
  'minneapolis': 'minnehaha falls minneapolis',
  'salt lake city': 'temple square salt lake city',
  'edmonton': 'west edmonton mall',
  'calgary': 'calgary tower',
  'ottawa': 'parliament hill ottawa',
  'winnipeg': 'canadian museum human rights winnipeg',
  'halifax': 'citadel hill halifax',
  'guadalajara': 'cathedral guadalajara',
  'monterrey': 'macroplaza monterrey',
  'cancun': 'chichen itza cancun',
  'panama city': 'panama canal miraflores',
  'san jose': 'national theatre costa rica',
  'quito': 'virgin el panecillo quito',
  'caracas': 'avila mountain caracas',
  'montevideo': 'independence plaza montevideo',
  'asuncion': 'national pantheon heroes asuncion',
  'la paz': 'illimani mountain la paz',

  // Asia
  'tokyo': 'mount fuji tokyo tower',
  'kyoto': 'kinkaku ji golden pavilion kyoto',
  'osaka': 'osaka castle dotonbori osaka',
  'beijing': 'great wall forbidden city beijing',
  'shanghai': 'the bund oriental pearl tower shanghai',
  'hong kong': 'victoria peak hong kong',
  'singapore': 'marina bay sands singapore',
  'seoul': 'gyeongbokgung palace seoul',
  'bangkok': 'grand palace wat phra kaew bangkok',
  'dubai': 'burj khalifa dubai',
  'istanbul': 'hagia sophia blue mosque istanbul',
  'mumbai': 'gateway of india mumbai',
  'delhi': 'taj mahal red fort delhi',
  'jerusalem': 'western wall dome of rock jerusalem',
  'taipei': 'taipei 101 taiwan',
  'hanoi': 'ha long bay hanoi',
  'kuala lumpur': 'petronas towers kuala lumpur',
  'abu dhabi': 'sheikh zayed mosque abu dhabi',
  'doha': 'pearl qatar doha',
  'jaipur': 'amber fort jaipur',
  'busan': 'haeundae beach busan',
  'sapporo': 'odori park sapporo',
  'nagoya': 'nagoya castle',
  'fukuoka': 'ohori park fukuoka',
  'guangzhou': 'canton tower guangzhou',
  'shenzhen': 'ping an finance center shenzhen',
  'chengdu': 'leshan giant buddha chengdu',
  'xian': 'terracotta warriors xian',
  'nanjing': 'purple mountain nanjing',
  'macau': 'ruins st pauls macau',
  'manila': 'intramuros manila',
  'jakarta': 'national monument jakarta',
  'ho chi minh': 'notre dame cathedral saigon',
  'phnom penh': 'royal palace phnom penh',
  'yangon': 'shwedagon pagoda yangon',
  'colombo': 'gangaramaya temple colombo',
  'dhaka': 'lalbagh fort dhaka',
  'kathmandu': 'swayambhunath stupa kathmandu',
  'thimphu': 'tashichho dzong thimphu',
  'ulaanbaatar': 'gandantegchinlen monastery ulaanbaatar',
  'almaty': 'kok tobe almaty',
  'tashkent': 'independence square tashkent',
  'ashgabat': 'independence monument ashgabat',
  'dushanbe': 'rudaki park dushanbe',
  'bishkek': 'ala too square bishkek',

  // Africa
  'cairo': 'pyramids sphinx giza cairo',
  'cape town': 'table mountain cape town',
  'marrakech': 'koutoubia mosque marrakech',
  'johannesburg': 'apartheid museum johannesburg',
  'nairobi': 'national park nairobi',
  'casablanca': 'hassan ii mosque casablanca',
  'alexandria': 'qaitbay citadel alexandria',
  'tunis': 'medina tunis',
  'algiers': 'grand mosque algiers',
  'dakar': 'african renaissance monument dakar',
  'addis ababa': 'holy trinity cathedral addis ababa',
  'lagos': 'national theatre lagos',
  'fez': 'medina fez',
  'rabat': 'hassan tower rabat',
  'khartoum': 'national museum sudan',
  'dar es salaam': 'azania front lutheran church',
  'kampala': 'kasubi tombs kampala',
  'accra': 'independence square accra',
  'abidjan': 'st paul cathedral abidjan',
  'kigali': 'genocide memorial kigali',
  'luanda': 'agostinho neto mausoleum luanda',
  'maputo': 'independence square maputo',
  'windhoek': 'christ church windhoek',
  'gaborone': 'three chiefs statue gaborone',
  'antananarivo': 'rova palace antananarivo',
  'lusaka': 'freedom statue lusaka',
  'harare': 'national heroes acre harare',
  'port louis': 'aapravasi ghat port louis',
  'bujumbura': 'living museum bujumbura',
  'libreville': 'leon mba memorial libreville',

  // Oceania
  'sydney': 'opera house harbour bridge sydney',
  'melbourne': 'flinders street station melbourne',
  'brisbane': 'story bridge brisbane',
  'auckland': 'sky tower auckland',
  'wellington': 'mount victoria wellington',
  'perth': 'elizabeth quay perth',
  'gold coast': 'surfers paradise gold coast',
  'adelaide': 'adelaide oval adelaide',
  'canberra': 'parliament house canberra',
  'christchurch': 'cathedral square christchurch',
  'hobart': 'mount wellington hobart',
  'darwin': 'mindil beach darwin',
  'cairns': 'great barrier reef cairns',
  'hamilton': 'hamilton gardens new zealand',
  'dunedin': 'railway station dunedin',
  'newcastle': 'nobbys beach newcastle',
  'wollongong': 'nan tien temple wollongong',
  'townsville': 'castle hill townsville',
  'suva': 'albert park suva',
  'port moresby': 'parliament haus port moresby'
};
